# Copyright (c) 2026, AG2ai, Inc., AG2ai open-source projects maintainers and core contributors
#
# SPDX-License-Identifier: Apache-2.0

import json
import types
import warnings
from collections.abc import Awaitable, Callable, Iterable
from contextlib import AsyncExitStack, ExitStack
from functools import partial
from itertools import chain
from typing import TYPE_CHECKING, Any, Generic, TypeAlias, TypeVar, overload

from fast_depends import Provider
from pydantic import ValidationError
from typing_extensions import TypeVar as TypeVar313

from autogen.beta.events import BinaryResult
from autogen.beta.tools.builtin.web_search import WEB_SEARCH_TOOL_NAME, WebSearchToolSchema

from .annotations import Context
from .config import LLMClient, ModelConfig
from .events import (
    BaseEvent,
    HumanInputRequest,
    Input,
    ModelRequest,
    ModelResponse,
    ToolResultsEvent,
)
from .events.conditions import Condition
from .exceptions import ConfigNotProvidedError
from .history import History
from .hitl import HumanHook, default_hitl_hook, wrap_hitl
from .middleware.base import AgentTurn, BaseMiddleware, LLMCall, MiddlewareFactory, ToolMiddleware
from .observer import Observer
from .observer import observer as observer_factory
from .response import ResponseProto, ResponseSchema
from .stream import MemoryStream, Stream
from .tools.executor import ToolExecutor
from .tools.final import FunctionParameters, FunctionTool, FunctionToolSchema, tool
from .tools.schemas import ToolSchema
from .tools.tool import Tool
from .types import ClassInfo, Omittable, omit
from .utils import CONTEXT_OPTION_NAME, build_model

if TYPE_CHECKING:
    from .conversable import ConversableAdapter
    from .tools.subagents import StreamFactory


TResult = TypeVar313("TResult", default=str)
TAgent = TypeVar313("TAgent", default=str)
T2 = TypeVar("T2")


class AgentReply(Generic[TResult, TAgent]):
    def __init__(
        self,
        response: ModelResponse,
        *,
        context: "Context",
        client: "LLMClient",
        agent: "Agent[TAgent]",
        provider: Provider | None,
        response_schema: ResponseProto[TResult] | None,
    ) -> None:
        self.response = response
        self.context = context
        self.__client = client
        self.__agent = agent
        self.__provider = provider
        self.__schema = response_schema

    async def content(
        self,
        *,
        retries: int | float = 0,
    ) -> TResult | None:
        schema = self.__schema
        if schema is None:
            return self.body  # type: ignore[return-value]

        max_retries = max(retries, 0)

        current = self
        attempt = 0

        while True:
            if current.body is None:
                return None

            attempt += 1
            try:
                return await schema.validate(
                    current.body,
                    context=current.context,
                    provider=current.__provider,
                )
            except ValidationError as e:
                if attempt > max_retries:
                    raise e

                schema_section = (
                    f"\n\n== Schema ==\n{json.dumps(schema.json_schema)}." if schema.json_schema is not None else ""
                )
                current = await current.ask(
                    "Your previous response could not be validated by schema."
                    f"{schema_section}"
                    "\n\nPlease try again."
                    "\n\n== Validation Error ==\n"
                    f"{e.json()}",
                    response_schema=schema,
                )

    @property
    def body(self) -> str | None:
        """Text body of the model's response for this turn."""
        return self.response.content

    @property
    def files(self) -> list[BinaryResult]:
        """Images generated by the model in this turn (decoded bytes)."""
        return self.response.files

    @property
    def history(self) -> History:
        return self.context.stream.history

    @overload
    async def ask(
        self,
        *msg: str | Input,
        dependencies: dict[Any, Any] | None = ...,
        variables: dict[Any, Any] | None = ...,
        prompt: Iterable[str] = ...,
        config: ModelConfig | None = ...,
        tools: Iterable[Tool] = ...,
        middleware: Iterable["MiddlewareFactory"] = ...,
        observers: Iterable[Observer] = ...,
        response_schema: type[T2],
        hitl_hook: HumanHook | None = ...,
    ) -> "AgentReply[T2, TAgent]": ...

    @overload
    async def ask(
        self,
        *msg: str | Input,
        dependencies: dict[Any, Any] | None = ...,
        variables: dict[Any, Any] | None = ...,
        prompt: Iterable[str] = ...,
        config: ModelConfig | None = ...,
        tools: Iterable[Tool] = ...,
        middleware: Iterable["MiddlewareFactory"] = ...,
        observers: Iterable[Observer] = ...,
        response_schema: ResponseProto[T2],
        hitl_hook: HumanHook | None = ...,
    ) -> "AgentReply[T2, TAgent]": ...

    @overload
    async def ask(
        self,
        *msg: str | Input,
        dependencies: dict[Any, Any] | None = ...,
        variables: dict[Any, Any] | None = ...,
        prompt: Iterable[str] = ...,
        config: ModelConfig | None = ...,
        tools: Iterable[Tool] = ...,
        middleware: Iterable["MiddlewareFactory"] = ...,
        observers: Iterable[Observer] = ...,
        response_schema: None,
        hitl_hook: HumanHook | None = ...,
    ) -> "AgentReply[str, TAgent]": ...

    @overload
    async def ask(
        self,
        *msg: str | Input,
        dependencies: dict[Any, Any] | None = ...,
        variables: dict[Any, Any] | None = ...,
        prompt: Iterable[str] = ...,
        config: ModelConfig | None = ...,
        tools: Iterable[Tool] = ...,
        middleware: Iterable["MiddlewareFactory"] = ...,
        observers: Iterable[Observer] = ...,
        hitl_hook: HumanHook | None = ...,
    ) -> "AgentReply[TAgent, TAgent]": ...

    async def ask(
        self,
        *msg: str | Input,
        dependencies: dict[Any, Any] | None = None,
        variables: dict[Any, Any] | None = None,
        prompt: Iterable[str] = (),
        config: ModelConfig | None = None,
        tools: Iterable[Tool] = (),
        middleware: Iterable["MiddlewareFactory"] = (),
        observers: Iterable[Observer] = (),
        response_schema: Omittable[ResponseProto[Any] | type | None] = omit,
        hitl_hook: HumanHook | None = None,
    ) -> "AgentReply[Any, Any]":
        initial_event = ModelRequest.ensure_request(list(msg))

        context = self.context
        if dependencies:
            context.dependencies.update(dependencies)
        if variables:
            context.variables.update(variables)
        if prompt:
            context.prompt = list(prompt)

        client = config.create() if config else self.__client

        return await self.__agent._execute(
            initial_event,
            context=context,
            client=client,
            hitl_hook=hitl_hook,
            additional_tools=tools,
            additional_middleware=middleware,
            additional_observers=observers,
            response_schema=response_schema,
        )


PromptHook: TypeAlias = Callable[..., str] | Callable[..., Awaitable[str]]
PromptType: TypeAlias = str | PromptHook


class Agent(Generic[TResult]):
    @overload
    def __init__(
        self,
        name: str,
        prompt: PromptType | Iterable[PromptType] = ...,
        *,
        config: ModelConfig | None = ...,
        hitl_hook: HumanHook | None = ...,
        tools: Iterable[Callable[..., Any] | Tool] = ...,
        middleware: Iterable["MiddlewareFactory"] = ...,
        observers: Iterable[Observer] = ...,
        dependencies: dict[Any, Any] | None = ...,
        variables: dict[Any, Any] | None = ...,
        response_schema: type[TResult],
        plugins: Iterable["Plugin"] = ...,
    ) -> None: ...

    @overload
    def __init__(
        self,
        name: str,
        prompt: PromptType | Iterable[PromptType] = ...,
        *,
        config: ModelConfig | None = ...,
        hitl_hook: HumanHook | None = ...,
        tools: Iterable[Callable[..., Any] | Tool] = ...,
        middleware: Iterable["MiddlewareFactory"] = ...,
        observers: Iterable[Observer] = ...,
        dependencies: dict[Any, Any] | None = ...,
        variables: dict[Any, Any] | None = ...,
        response_schema: ResponseProto[TResult],
        plugins: Iterable["Plugin"] = ...,
    ) -> None: ...

    @overload
    def __init__(
        self,
        name: str,
        prompt: PromptType | Iterable[PromptType] = ...,
        *,
        config: ModelConfig | None = ...,
        hitl_hook: HumanHook | None = ...,
        tools: Iterable[Callable[..., Any] | Tool] = ...,
        middleware: Iterable["MiddlewareFactory"] = ...,
        observers: Iterable[Observer] = ...,
        dependencies: dict[Any, Any] | None = ...,
        variables: dict[Any, Any] | None = ...,
        response_schema: types.UnionType,
        plugins: Iterable["Plugin"] = ...,
    ) -> None: ...

    @overload
    def __init__(
        self,
        name: str,
        prompt: PromptType | Iterable[PromptType] = ...,
        *,
        config: ModelConfig | None = ...,
        hitl_hook: HumanHook | None = ...,
        tools: Iterable[Callable[..., Any] | Tool] = ...,
        middleware: Iterable["MiddlewareFactory"] = ...,
        observers: Iterable[Observer] = ...,
        dependencies: dict[Any, Any] | None = ...,
        variables: dict[Any, Any] | None = ...,
        response_schema: None = ...,
        plugins: Iterable["Plugin"] = ...,
    ) -> None: ...

    def __init__(
        self,
        name: str,
        prompt: PromptType | Iterable[PromptType] = (),
        *,
        config: ModelConfig | None = None,
        hitl_hook: HumanHook | None = None,
        tools: Iterable[Callable[..., Any] | Tool] = (),
        middleware: Iterable["MiddlewareFactory"] = (),
        observers: Iterable[Observer] = (),
        dependencies: dict[Any, Any] | None = None,
        variables: dict[Any, Any] | None = None,
        response_schema: ResponseProto[TResult] | type[TResult] | types.UnionType | None = None,
        plugins: Iterable["Plugin"] = (),
    ):
        self.name = name
        self.config = config

        self._agent_dependencies = dependencies or {}
        self._agent_variables = variables or {}

        self._middleware = list(middleware)
        self._observers = list(observers)

        self.dependency_provider = Provider()
        self.tools: list[FunctionTool] = []
        for t in tools:
            self.add_tool(t)

        self._hitl_hook = wrap_hitl(hitl_hook) if hitl_hook else None
        self.__tool_executor = ToolExecutor()

        self._system_prompt: list[str] = []
        self._dynamic_prompt: list[Callable[[ModelRequest, Context], Awaitable[str]]] = []

        self._response_schema = ResponseSchema.ensure_schema(response_schema)

        if isinstance(prompt, str) or callable(prompt):
            prompt = [prompt]

        for p in prompt:
            if isinstance(p, str):
                self._system_prompt.append(p)
            else:
                self._dynamic_prompt.append(_wrap_prompt_hook(p))

        for p in plugins:
            p.register(self)

    def hitl_hook(self, func: HumanHook) -> HumanHook:
        if self._hitl_hook is not None:
            warnings.warn(
                "You already set HITL hook, provided value overrides it",
                category=RuntimeWarning,
                stacklevel=2,
            )

        self._hitl_hook = wrap_hitl(func)
        return func

    @overload
    def prompt(
        self,
        func: None = None,
    ) -> Callable[[PromptHook], PromptHook]: ...

    @overload
    def prompt(
        self,
        func: PromptHook,
    ) -> PromptHook: ...

    def prompt(
        self,
        func: PromptHook | None = None,
    ) -> PromptHook | Callable[[PromptHook], PromptHook]:
        def wrapper(f: PromptHook) -> PromptHook:
            self._dynamic_prompt.append(_wrap_prompt_hook(f))
            return f

        if func:
            return wrapper(func)
        return wrapper

    @overload
    def tool(
        self,
        function: Callable[..., Any],
        *,
        name: str | None = None,
        description: str | None = None,
        schema: FunctionParameters | None = None,
        sync_to_thread: bool = True,
        middleware: Iterable[ToolMiddleware] = (),
    ) -> Tool: ...

    @overload
    def tool(
        self,
        function: None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        schema: FunctionParameters | None = None,
        sync_to_thread: bool = True,
        middleware: Iterable[ToolMiddleware] = (),
    ) -> Callable[[Callable[..., Any]], Tool]: ...

    def add_middleware(self, m: MiddlewareFactory) -> "Agent[TResult]":
        """Append middleware as the innermost wrapper in the chain.

        The added middleware is called last on turn entry and first on turn exit,
        executing closer to the LLM call than any middleware already registered.
        """
        self._middleware.append(m)
        return self

    def insert_middleware(self, m: MiddlewareFactory) -> "Agent[TResult]":
        """Insert middleware as the outermost wrapper in the chain.

        The inserted middleware is called first on turn entry and last on turn exit,
        executing before all middleware already registered on the agent.
        """
        self._middleware.insert(0, m)
        return self

    def add_tool(self, t: Callable[..., Any] | Tool) -> "Agent[TResult]":
        self.tools.append(FunctionTool.ensure_tool(t, provider=self.dependency_provider))
        return self

    def tool(
        self,
        function: Callable[..., Any] | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        schema: FunctionParameters | None = None,
        sync_to_thread: bool = True,
        middleware: Iterable[ToolMiddleware] = (),
    ) -> Tool | Callable[[Callable[..., Any]], Tool]:
        def make_tool(f: Callable[..., Any]) -> Tool:
            t = tool(
                f,
                name=name,
                description=description,
                schema=schema,
                sync_to_thread=sync_to_thread,
                middleware=middleware,
            )
            self.add_tool(t)
            return t

        if function:
            return make_tool(function)

        return make_tool

    @overload
    def observer(
        self,
        condition: ClassInfo | Condition,
        callback: Callable[..., Any],
    ) -> Callable[..., Any]: ...

    @overload
    def observer(
        self,
        condition: ClassInfo | Condition,
    ) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...

    def observer(
        self,
        condition: ClassInfo | Condition,
        callback: Callable[..., Any] | None = None,
    ) -> Callable[..., Any] | Callable[[Callable[..., Any]], Callable[..., Any]]:
        def wrapper(func: Callable[..., Any]) -> Callable[..., Any]:
            obs = observer_factory(condition, func)
            self._observers.append(obs)
            return func

        if callback is not None:
            return wrapper(callback)
        return wrapper

    @overload
    async def ask(
        self,
        *msg: str | Input,
        stream: Stream | None = ...,
        dependencies: dict[Any, Any] | None = ...,
        variables: dict[Any, Any] | None = ...,
        prompt: Iterable[str] = ...,
        config: ModelConfig | None = ...,
        tools: Iterable[Tool] = ...,
        middleware: Iterable["MiddlewareFactory"] = ...,
        observers: Iterable[Observer] = ...,
        response_schema: type[T2],
        hitl_hook: HumanHook | None = ...,
    ) -> "AgentReply[T2, TResult]": ...

    @overload
    async def ask(
        self,
        msg: str | Input,
        *,
        stream: Stream | None = ...,
        dependencies: dict[Any, Any] | None = ...,
        variables: dict[Any, Any] | None = ...,
        prompt: Iterable[str] = ...,
        config: ModelConfig | None = ...,
        tools: Iterable[Tool] = ...,
        middleware: Iterable["MiddlewareFactory"] = ...,
        observers: Iterable[Observer] = ...,
        response_schema: ResponseProto[T2],
        hitl_hook: HumanHook | None = ...,
    ) -> "AgentReply[T2, TResult]": ...

    @overload
    async def ask(
        self,
        msg: str | Input,
        *,
        stream: Stream | None = ...,
        dependencies: dict[Any, Any] | None = ...,
        variables: dict[Any, Any] | None = ...,
        prompt: Iterable[str] = ...,
        config: ModelConfig | None = ...,
        tools: Iterable[Tool] = ...,
        middleware: Iterable["MiddlewareFactory"] = ...,
        observers: Iterable[Observer] = ...,
        response_schema: None,
        hitl_hook: HumanHook | None = ...,
    ) -> "AgentReply[str, TResult]": ...

    @overload
    async def ask(
        self,
        msg: str | Input,
        *,
        stream: Stream | None = ...,
        dependencies: dict[Any, Any] | None = ...,
        variables: dict[Any, Any] | None = ...,
        prompt: Iterable[str] = ...,
        config: ModelConfig | None = ...,
        tools: Iterable[Tool] = ...,
        middleware: Iterable["MiddlewareFactory"] = ...,
        observers: Iterable[Observer] = ...,
        hitl_hook: HumanHook | None = ...,
    ) -> "AgentReply[TResult, TResult]": ...

    async def ask(
        self,
        *msg: str | Input,
        stream: Stream | None = None,
        dependencies: dict[Any, Any] | None = None,
        variables: dict[Any, Any] | None = None,
        prompt: Iterable[str] = (),
        config: ModelConfig | None = None,
        tools: Iterable[Tool] = (),
        middleware: Iterable["MiddlewareFactory"] = (),
        observers: Iterable[Observer] = (),
        response_schema: Omittable[ResponseProto[Any] | type | None] = omit,
        hitl_hook: HumanHook | None = None,
    ) -> "AgentReply[Any, Any]":
        config = config or self.config
        if not config:
            raise ConfigNotProvidedError()
        client = config.create()

        stream = stream or MemoryStream()

        initial_event = ModelRequest.ensure_request(msg)

        context = Context(
            stream,
            prompt=list(prompt),
            dependencies=self._agent_dependencies | (dependencies or {}),
            variables=self._agent_variables | (variables or {}),
            dependency_provider=self.dependency_provider,
        )

        if not context.prompt:
            context.prompt.extend(self._system_prompt)

            for dp in self._dynamic_prompt:
                p = await dp(initial_event, context)
                context.prompt.append(p)

        return await self._execute(
            initial_event,
            context=context,
            client=client,
            hitl_hook=hitl_hook,
            additional_tools=tools,
            additional_middleware=middleware,
            additional_observers=observers,
            response_schema=response_schema,
        )

    async def _execute(
        self,
        event: BaseEvent,
        *,
        context: Context,
        client: LLMClient,
        hitl_hook: HumanHook | None = None,
        additional_tools: Iterable[Tool] = (),
        additional_middleware: Iterable["MiddlewareFactory"] = (),
        additional_observers: Iterable[Observer] = (),
        response_schema: Omittable[ResponseProto[Any] | type | None] = omit,
    ) -> "AgentReply[Any, Any]":
        if response_schema is omit:
            final_schema = self._response_schema
        else:
            final_schema = ResponseSchema.ensure_schema(response_schema)

        all_tools: list[Tool] = list(
            chain(
                self.tools,
                additional_tools,
            )
        )

        all_schemas: list[ToolSchema] = []
        known_tools: set[str] = set()
        for t in all_tools:
            schemas = await t.schemas(context)
            all_schemas.extend(schemas)

            for schema in schemas:
                if isinstance(schema, FunctionToolSchema):
                    known_tools.add(schema.function.name)
                elif isinstance(schema, WebSearchToolSchema):
                    known_tools.add(WEB_SEARCH_TOOL_NAME)

        middleware_instances: list[BaseMiddleware] = []
        agent_turn: AgentTurn = _execute_turn
        llm_call: LLMCall = partial(
            client,
            tools=all_schemas,
            response_schema=final_schema,
        )

        for m in reversed(
            list(
                chain(
                    self._middleware,
                    additional_middleware,
                )
            )
        ):
            mw = m(event, context)
            middleware_instances.append(mw)

            agent_turn = partial(mw.on_turn, agent_turn)
            llm_call = partial(mw.on_llm_call, llm_call)

        async def _call_client(context: Context) -> None:
            messages = await context.stream.history.get_events()
            result = await llm_call(messages, context)
            await context.send(result)

        with ExitStack() as stack:
            stack.enter_context(
                context.stream.where(ModelRequest | ToolResultsEvent).sub_scope(_call_client),
            )

            hitl_hook_maker = wrap_hitl(hitl_hook) if hitl_hook else self._hitl_hook
            if hitl_hook_maker is not None:
                stack.enter_context(
                    context.stream.where(HumanInputRequest).sub_scope(
                        hitl_hook_maker(middleware_instances),
                        interrupt=True,
                    ),
                )

            else:
                stack.enter_context(
                    context.stream.where(HumanInputRequest).sub_scope(
                        default_hitl_hook(middleware_instances),
                    ),
                )

            self.__tool_executor.register(
                stack,
                context,
                tools=all_tools,
                known_tools=known_tools,
                middleware=middleware_instances,
            )

            for obs in chain(self._observers, additional_observers):
                obs.register(stack, context)

            message = await agent_turn(event, context)

            return AgentReply(
                message,
                context=context,
                agent=self,
                client=client,
                provider=self.dependency_provider,
                response_schema=final_schema,
            )

    def as_tool(
        self,
        *,
        description: str,
        name: str | None = None,
        stream: "StreamFactory | None" = None,
        middleware: Iterable[ToolMiddleware] = (),
    ) -> FunctionTool:
        from .tools.subagents import subagent_tool

        return subagent_tool(
            self,
            description=description,
            name=name,
            stream=stream,
            middleware=middleware,
        )

    def as_conversable(self) -> "ConversableAdapter":
        from .conversable import ConversableAdapter

        return ConversableAdapter(self)


async def _execute_turn(event: BaseEvent, context: Context) -> ModelResponse:
    async with context.stream.get(ModelResponse) as result:
        await context.send(event)
        message: ModelResponse = await result

    while message.tool_calls and not message.response_force:
        async with context.stream.get(ModelResponse) as result:
            await context.send(message.tool_calls)
            message = await result

    return message


def _wrap_prompt_hook(func: PromptHook) -> Callable[[ModelRequest, Context], Awaitable[str]]:
    call_model = build_model(func)

    async def wrapper(event: ModelRequest, context: Context) -> str:
        async with AsyncExitStack() as stack:
            r = await call_model.asolve(
                event,
                stack=stack,
                cache_dependencies={},
                dependency_provider=context.dependency_provider,
                **{CONTEXT_OPTION_NAME: context},
            )
        return r

    return wrapper


class Plugin:
    def __init__(
        self,
        *,
        prompt: PromptType | Iterable[PromptType] = (),
        hitl_hook: HumanHook | None = None,
        tools: Iterable[Callable[..., Any] | Tool] = (),
        middleware: Iterable[MiddlewareFactory] = (),
        observers: Iterable[Observer] = (),
        dependencies: dict[Any, Any] | None = None,
        variables: dict[Any, Any] | None = None,
    ) -> None:
        self._tools = list(tools)
        self._middleware = list(middleware)
        self._observers = list(observers)
        self._dependencies = dependencies or {}
        self._variables = variables or {}
        self._hitl_hook = hitl_hook

        self._system_prompt: list[str] = []
        self._dynamic_prompt: list[Callable[[ModelRequest, Context], Awaitable[str]]] = []

        if isinstance(prompt, str) or callable(prompt):
            prompt = [prompt]
        for p in prompt:
            if isinstance(p, str):
                self._system_prompt.append(p)
            else:
                self._dynamic_prompt.append(_wrap_prompt_hook(p))

    def register(self, agent: "Agent[Any]") -> None:
        """Apply this plugin's contributions to an Agent instance."""
        for t in self._tools:
            agent.add_tool(t)

        for m in self._middleware:
            agent.add_middleware(m)

        if self._hitl_hook is not None:
            if agent._hitl_hook is not None:
                warnings.warn(
                    f"Agent '{agent.name}' already has a HITL hook; the plugin's hook will be ignored.",
                    stacklevel=2,
                )
            else:
                agent._hitl_hook = wrap_hitl(self._hitl_hook)

        agent._agent_dependencies = self._dependencies | agent._agent_dependencies
        agent._agent_variables.update(self._variables)

        agent._observers.extend(self._observers)
        agent._system_prompt.extend(self._system_prompt)
        agent._dynamic_prompt.extend(self._dynamic_prompt)

    def hitl_hook(self, func: HumanHook) -> HumanHook:
        if self._hitl_hook is not None:
            warnings.warn(
                "You already set HITL hook, provided value overrides it",
                category=RuntimeWarning,
                stacklevel=2,
            )
        self._hitl_hook = func
        return func

    @overload
    def prompt(
        self,
        func: PromptHook,
    ) -> PromptHook: ...

    @overload
    def prompt(
        self,
        func: None = None,
    ) -> Callable[[PromptHook], PromptHook]: ...

    def prompt(
        self,
        func: PromptHook | None = None,
    ) -> PromptHook | Callable[[PromptHook], PromptHook]:
        def wrapper(f: PromptHook) -> PromptHook:
            self._dynamic_prompt.append(_wrap_prompt_hook(f))
            return f

        if func:
            return wrapper(func)
        return wrapper

    @overload
    def tool(
        self,
        function: Callable[..., Any],
        *,
        name: str | None = None,
        description: str | None = None,
        schema: FunctionParameters | None = None,
        sync_to_thread: bool = True,
        middleware: Iterable[ToolMiddleware] = (),
    ) -> FunctionTool: ...

    @overload
    def tool(
        self,
        function: None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        schema: FunctionParameters | None = None,
        sync_to_thread: bool = True,
        middleware: Iterable[ToolMiddleware] = (),
    ) -> Callable[[Callable[..., Any]], FunctionTool]: ...

    def tool(
        self,
        function: Callable[..., Any] | None = None,
        *,
        name: str | None = None,
        description: str | None = None,
        schema: FunctionParameters | None = None,
        sync_to_thread: bool = True,
        middleware: Iterable[ToolMiddleware] = (),
    ) -> FunctionTool | Callable[[Callable[..., Any]], FunctionTool]:
        def make_tool(f: Callable[..., Any]) -> FunctionTool:
            t = tool(
                f,
                name=name,
                description=description,
                schema=schema,
                sync_to_thread=sync_to_thread,
                middleware=middleware,
            )
            self._tools.append(t)
            return t

        if function:
            return make_tool(function)
        return make_tool

    @overload
    def observer(
        self,
        condition: ClassInfo | Condition,
        callback: Callable[..., Any],
    ) -> Callable[..., Any]: ...

    @overload
    def observer(
        self,
        condition: ClassInfo | Condition,
    ) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...

    def observer(
        self,
        condition: ClassInfo | Condition,
        callback: Callable[..., Any] | None = None,
    ) -> Callable[..., Any] | Callable[[Callable[..., Any]], Callable[..., Any]]:
        def wrapper(func: Callable[..., Any]) -> Callable[..., Any]:
            obs = observer_factory(condition, func)
            self._observers.append(obs)
            return func

        if callback is not None:
            return wrapper(callback)
        return wrapper
