name: Build MkDocs

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        required: true
        default: '3.10'
        type: string

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          lfs: true
          fetch-depth: 0
      - uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0
        with:
          version: "latest"
      - name: setup python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ github.event.inputs.python-version }}

      - name: Install quarto
        uses: quarto-dev/quarto-actions/setup@8a96df13519ee81fd526f2dfca5962811136661b # v2.2.0

      - uses: extractions/setup-just@dd310ad5a97d8e7b41793f8ef055398d51ad4de6 # v2.0.0
      - name: Build MkDocs documentation
        run: |
          uv venv
          . .venv/bin/activate
          uv pip install -e ".[docs]"
          just docs-build --force
        working-directory: .

      - name: Verify the build
        run: |
          ls -la ./website/mkdocs/site
        working-directory: .

      - name: Configure Git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Deploy docs to GH Pages
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/0.9'
        run: |
          . .venv/bin/activate

          # Get version directly from the package
          VERSION=$(python -c 'import os, sys; sys.path.insert(0, os.getcwd()); import autogen; print(".".join(autogen.__version__.split(".")[:3]))')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

          # Check if version contains "rc"
          IS_RC=$(python -c 'import os, sys, re; sys.path.insert(0, os.getcwd()); import autogen; version = autogen.__version__; print(not bool(re.match(r"^[0-9]+(\.[0-9]+)*$", version)))')
          echo "IS_RC=$IS_RC" >> $GITHUB_ENV

          echo $VERSION
          echo $IS_RC

          if [ "$IS_RC" == "False" ] || [ "$VERSION" == "0.9.1post0" ]; then
            cd website/mkdocs && mike deploy -F mkdocs.yml --update-aliases $VERSION latest
            mike set-default --push --allow-empty -F mkdocs.yml latest
          else
            cd website/mkdocs && mike deploy --push -F mkdocs.yml --update-aliases $VERSION
          fi
